### ISSUE TITLE
[Feature Request]: Pagination

### ISSUE THREAD

**Issue by TheAwiteb** [X7md/x7md.github.io#16]
# Pagination
There is no pagination, that means more time to load the page ( if i have more than 15 post )

## Tasks

- [ ] Add pagination in main posts page
- [ ] Add pagination in topics page #15
- [ ] beautiful ui for it ( @X7md 👀 )

**Comment by X7md** [comment]
I don't think that good, maybe on the future I will thinking on adding `Pagination` but for now I don't think we need it actually?

**Comment by TheAwiteb** [comment]
👍🏻
